### ISSUE TITLE
Ensure all requests have the X-frame-options header sent.

### ISSUE THREAD

**Issue by pburkholder** [cloud-gov/cg-deploy-prometheus#169]
In order to close POA&M 2019-V0028-RA-5 we want to ensure _every_ response has XFO (X-Frame-Options) header set.

These URLs don't:

```
https://alertmanager.fr.cloud.gov/oauth2/sign_in
https://grafana.fr.cloud.gov/oauth2/sign_in
https://prometheus.fr.cloud.gov/oauth2/sign_in
```

This may be addressable in https://github.com/cloud-gov/cg-deploy-prometheus/blob/main/bosh/manifest.yml

 
## Security considerations
Adding XFO is an improvement. 

## Implementation sketch
See slack conversation at https://gsa-tts.slack.com/archives/GNSL334HM/p1640887053011600

**Comment by pburkholder** [comment]
This is now called "Anti-clickjacking..." in ZAP, and we can resolve with either of these headers:

```
content-security-policy: frame-ancestors 'none'
x-frame-options: deny
```

**Comment by pburkholder** [comment]
The ZAP scans this month didn't have this finding, but when I go in-browser to https://alertmanager.fr.cloud.gov/oauth2/sign_in as an authenticated use, the response is indeed missing 

> x-frame-options: DENY

**Comment by ChrisMcGowan** [comment]
@pburkholder this is now done.

For reference on the PR for the `oauth` package change: https://github.com/cloud-gov/oauth2-proxy-boshrelease/pull/16
We also now front end `oauth` with `secureproxy` : https://github.com/cloud-gov/cg-deploy-prometheus/pull/177

That gives us the same headers we use on other spots on the platform.
